[versions]
kotlin = "1.6.10"
coroutines = "1.6.0"

[libraries.kotlin-gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"

[libraries.kotlinx-coroutines-core]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"

[libraries.kotlinx-coroutines-android]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-android"

[libraries.kotlinx-coroutines-test]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"
