on:
  push:
    tags: ['*']
name: Release
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2.3.1
            -
                name: Build
                run: ./gradlew build
            -
                name: Publish
                env:
                    GITHUB_TAG: ${{ github.ref }}
                    ORG_GRADLE_PROJECT_mavenUser: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                    ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
                    ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.PGP_INK_CI_KEYID }}
                    ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_INK_CI_PRIVATE }}
                    ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_INK_CI_PASSWORD }}
                run: ./gradlew publishAllPublicationsToMavenCentralRepository -Pversion=${GITHUB_TAG/refs\/tags\//}
